create table employees(
id serial primary key,
employee_name varchar(50) not null);

insert into employees(employee_name)
values ('Michael'),
	   ('Christopher'),
	   ('Jason'),
	   ('David'),
	   ('James'),
	   ('John'),
	   ('Robert'),
	   ('Brian'),
	   ('William'),
	   ('Matthew'),
	   ('Joseph'),
	   ('Daniel'),
	   ('Kevin'),
	   ('Eric'),
	   ('Jeffrey'),
	   ('Richard'),
	   ('Scott'),
	   ('Mark'),
	   ('Steven'),
	   ('Thomas'),
	   ('Timothy'),
	   ('Anthony'),
	   ('Charles'),
	   ('Joshua'),
	   ('Ryan'),
	   ('Jeremy'),
	   ('Paul'),
	   ('Andrew'),
	   ('Gregory'),
	   ('Chad'),
	   ('Kenneth'),
	   ('Jonathan'),
	   ('Stephen'),
	   ('Shawn'),
	   ('Aaron'),
	   ('Adam'),
	   ('Patrick'),
	   ('Justin'),
	   ('Sean'),
	   ('Edward'),
	   ('Todd'),
	   ('Donald'),
	   ('Ronald'),
	   ('Benjamin'),
	   ('Keith'),
	   ('Bryan'),
	   ('Gary'),
	   ('Jose'),
	   ('Nathan'),
	   ('Douglas'),
	   ('Nicholas'),
	   ('Brandon'),
	   ('George'),
	   ('Travis'),
	   ('Peter'),
	   ('Craig'),
	   ('Bradley'),
	   ('Larry'),
	   ('Dennis'),
	   ('Shane'),
	   ('Raymond'),
	   ('Troy'),
	   ('Jerry'),
	   ('Samuel'),
	   ('Frank'),
	   ('Jesse'),
	   ('Jeffery'),
	   ('Juan'),
	   ('Terry'),
	   ('Corey');
	   
select*from employees;

create table salary(
id serial primary key,
monthly_salary int not null);

insert into salary(monthly_salary)
values (1000),
	   (1100),
	   (1200),
	   (1300),
	   (1400),
	   (1500),
	   (1600),
	   (1700),
	   (1800),
	   (1900),
	   (2000),
	   (2100),
	   (2200),
	   (2300),
	   (2400),
	   (2500);
	  
select*from salary;

create table employee_salary(
id serial primary key,
employee_id int unique not null,
salary_id int not null);

insert into employee_salary(employee_id, salary_id)
values (3, 7),
	   (1, 4),
	   (5, 9),
	   (40, 13),
	   (23, 4),
	   (11, 2),
	   (52, 10),
	   (15, 13),
	   (26, 4),
	   (16, 1),
	   (33, 7),
	   (2, 3),
	   (4, 5),
	   (6, 6),
	   (7, 8),
	   (8, 11),
	   (9, 12),
	   (10, 14),
	   (12, 15),
	   (13, 16),
	   (14, 2),
	   (17, 10),
	   (18, 9),
	   (22, 8),
	   (28, 11),
	   (30, 16),
	   (31, 14),
	   (32, 3),
	   (35, 1),
	   (41, 9),
	   (71, 13),
	   (75, 15),
	   (76, 8),
	   (79, 13),
	   (80, 11),
	   (83, 12),
	   (86, 6),
	   (88, 16),
	   (90, 2),
	   (95, 4);

select * from employee_salary;

create table roles(
id serial primary key,
role_name int unique not null);

alter table roles alter column role_name type varchar(30);

select * from roles; 

insert into roles (role_name)
values ('Junior_Python_developer'),
       ('Middle_Python_developer'),
       ('Senior_Python_developer'),
       ('Junior_Java_developer'),
       ('Middle_Java_developer'),
       ('Senior_Java_developer'),
       ('Junior_JavaScript_developer'),
       ('Middle_JavaScript_developer'),
       ('Senior_JavaScript_developer'),
       ('Junior_Manual_QA_engineer'),
       ('Middle_Manual_QA_engineer'),
       ('Senior_Manual_QA_engineer'),
       ('Project_Manager'),
       ('Designer'),
       ('HR'),
       ('CEO'),
       ('Sales_manager'),
       ('Junior_Automation_QA_engineer'),
       ('Middle_Automation_QA_engineer'),
       ('Senior_Automation_QA_engineer');

select * from roles;

create table roles_employee (
         id serial primary key,
         employee_id int unique not null,
         role_id int not null,
         foreign key (employee_id)
             references employees(id),
         foreign key (role_id)
             references roles(id));

insert into roles_employee(employee_id, role_id)
	 values (7, 2),
	 		(20, 4),
	 		(3, 9),
	 		(5, 13),
	 		(23, 4),
	 		(11, 2),
	 		(10, 9),
	 		(22, 13),
	 		(21, 3),
	 		(34, 4),
	 		(6, 7),
	 		(12, 12),
	 		(13, 13),
	 		(14, 14),
	 		(15, 15),
	 		(16, 16),
	 		(17, 17),
	 		(18, 18),
	 		(19, 19),
	 		(41, 20),
	 		(48, 1),
	 		(43, 2),
	 		(42, 3),
	 		(24, 4),
	 		(25, 5),
	 		(26, 6),
	 		(27, 7),
	 		(28, 8),
	 		(29, 9),
	 		(30, 10),
	 		(31, 11),
	 		(32, 12),
	 		(33, 13),
	 		(44, 14),
	 		(35, 15),
	 		(36, 16),
	 		(37, 17),
	 		(38, 18),
	 		(39, 19),
	 		(40, 20);
	 	
select * from roles_employee;
